# Generated by Django 5.2.5 on 2025-08-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
