### Post Request to create an offer as business user
POST http://127.0.0.1:8000/api/offers/
Content-Type: application/json
Authorization: Token 79325e91ed0611554f2396d8a3507ef359a14651

{
  "title": "Webentwicklung-Paket",
  "image": null,
  "description": "Professionelles Webentwicklungspaket für Ihre Online-Präsenz.",
  "details": [
    {
      "title": "Basic Website",
      "revisions": 1,
      "delivery_time_in_days": 7,
      "price": 300,
      "features": [
        "1 Seite",
        "Responsive Design"
      ],
      "offer_type": "basic"
    },
    {
      "title": "Standard Website",
      "revisions": 3,
      "delivery_time_in_days": 14,
      "price": 600,
      "features": [
        "Bis zu 5 Seiten",
        "Responsive Design",
        "Kontaktformular"
      ],
      "offer_type": "standard"
    },
    {
      "title": "Premium Website",
      "revisions": 5,
      "delivery_time_in_days": 21,
      "price": 1200,
      "features": [
        "Bis zu 10 Seiten",
        "Responsive Design",
        "Kontaktformular",
        "SEO Optimierung"
      ],
      "offer_type": "premium"
    }
  ]
}

### Post Request to create an offer as customer
POST http://127.0.0.1:8000/api/offers/
Content-Type: application/json
Authorization: Token 66451c9a18248bc4ffdad82d78dedf675e18c26b

{
  "title": "Social Media Marketing Paket",
  "image": null,
  "description": "Effektive Marketingstrategien für Ihre Social-Media-Kanäle.",
  "details": [
    {
      "title": "Basic Marketing",
      "revisions": 2,
      "delivery_time_in_days": 5,
      "price": 150,
      "features": [
        "2 Beiträge pro Woche",
        "Content Planung"
      ],
      "offer_type": "basic"
    },
    {
      "title": "Standard Marketing",
      "revisions": 4,
      "delivery_time_in_days": 10,
      "price": 350,
      "features": [
        "5 Beiträge pro Woche",
        "Content Planung",
        "Community Management"
      ],
      "offer_type": "standard"
    },
    {
      "title": "Premium Marketing",
      "revisions": 7,
      "delivery_time_in_days": 15,
      "price": 700,
      "features": [
        "Tägliche Beiträge",
        "Content Planung",
        "Community Management",
        "Werbekampagnen"
      ],
      "offer_type": "premium"
    }
  ]
}
