# Generated by Django 5.2.5 on 2025-08-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0002_alter_offerdetail_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
